<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: starting data (starting random weights?)
### Hidden Layer:  intermediate calculation results between input and output
### Output Layer:  final result(s)
### Neuron:  handle a value in any layer
### Weight:  scale the value of a signal to test or represent which inputs are important
### Activation Function:  decides how incoming values * weights affect outgoing values for any nueron or layer
### Node Map:  the combinations of paths inputs can influece
### Perceptron:  a single calculation neural network, repeated to get better accuracy

So does every connection in the net have a random starting weight, that repeated testing can attempt to improve?  How does it keep track of all the weight adjustments to make with multiple layers?
Theres no reason for a node to omit an input, cuz it could always weight it to zero/negative for the same affect.
Multiple nodes in a layer could be for calculation efficiency vs extra layers?, or, to store many values if you cant refernce orginal inputs past the first layer, though with enough layers maybe only input + 1 nodes are ever needed per layer.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

I don't know about bias - in the lesson it seemed like at one point bias was referred to as one of the inputs (3rd binary value was the bias?).  Other option might be as a base value for any weight * input to get added onto between neurons, but that could cause a normalization problems.

Otherwise, input => multiplication by weights => sum of all input/weight pairs => activation amplification/threshold => output value (becomes next layer input)

What prevents multiple neurons in a layer from picking the same/similar weights?

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import numpy as np
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [2]:
inputs = np.array(df[['x1', 'x2']])
# correct_outputs = np.array(df['y'])
correct_outputs = []
for yval in (df['y']):
    correct_outputs.append([yval])

correct_outputs

[[1], [1], [1], [0]]

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [4]:
weights = 2 * np.random.random((2, 1)) - 1
weights

array([[0.44813536],
       [0.16512411]])

In [5]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.        ],
       [0.44813536],
       [0.16512411],
       [0.61325947]])

In [6]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.61019581],
       [0.54118749],
       [0.64868397]])

In [7]:
error = correct_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.38980419],
       [ 0.45881251],
       [-0.64868397]])

In [8]:
adjusted = error * sigmoid_derivative(activated_output)
adjusted

array([[ 0.11750186],
       [ 0.08891445],
       [ 0.10669804],
       [-0.14623982]])

In [63]:
weights += np.dot(inputs.T, adjusted)
weights
bias = 9

In [64]:
for interation in range(10000):
    weighted_sum = np.dot(inputs, weights) + bias
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjusted = error * sigmoid_derivative(activated_output)
    weights += np.dot(inputs.T, adjusted)

print('weights')
print(weights)
print('results')
print(activated_output)
for result in activated_output:
    print(round(result[0], 0))
print('error', error)

weights
[[-6.0757273]
 [-6.0757273]]
results
[[0.99987661]
 [0.94903336]
 [0.94903336]
 [0.041034  ]]
1.0
1.0
1.0
0.0
error [[ 0.00012339]
 [ 0.05096664]
 [ 0.05096664]
 [-0.041034  ]]


In [36]:
weights = 2 * [[np.random.randint(-1, 2)]] 
weights

[[0], [0]]

In [37]:
for interation in range(10):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
#     adjusted = error * sigmoid_derivative(activated_output)
#     weights += np.dot(inputs.T, adjusted)
    weights = 2 * [[np.random.randint(-1, 2)]]
    print('result', activated_output)
    print('error', error)

result [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error [[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
result [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error [[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
result [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error [[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
result [[0.5       ]
 [0.73105858]
 [0.73105858]
 [0.88079708]]
error [[ 0.5       ]
 [ 0.26894142]
 [ 0.26894142]
 [-0.88079708]]
result [[0.5       ]
 [0.26894142]
 [0.26894142]
 [0.11920292]]
error [[ 0.5       ]
 [ 0.73105858]
 [ 0.73105858]
 [-0.11920292]]
result [[0.5       ]
 [0.73105858]
 [0.73105858]
 [0.88079708]]
error [[ 0.5       ]
 [ 0.26894142]
 [ 0.26894142]
 [-0.88079708]]
result [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error [[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
result [[0.5]
 [0.5]
 [0.5]
 [0.5]]
error [[ 0.5]
 [ 0.5]
 [ 0.5]
 [-0.5]]
result [[0.5       ]
 [0.73105858]
 [0.73105858]
 [0.88079708]]
error [[ 0.5       ]
 [ 0.26894142]
 [ 0.26894142]
 [-0.88079708]]
result [[0.5       ]
 [0.73105858]
 [0.73105858]
 [0.88079708]]
error [[ 0.5       ]
 [ 0.26894142]
 

It seems like I need more than one neuron.  Or do I not have enough weights?

So it wants me to bias the result toward 1, and then weight everything negative so when both inputs are 1 the result goes down.  Why doesn't it randomly try bias, like weights? Or was that the point?  Is there a way to do error adjustment on the bias?

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [13]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [22]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

transformer = Normalizer().fit(diabetes[feats])

# X = ...

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [42]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        pass

    # Randomly Initialize Weights
    weights = 2 * np.random.random((2, 1)) - 1

    for i in range(self.niter):
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(inputs, weights)
        # Activate!
        activated_output = sigmoid(weighted_sum)
        # Cac error
        error = correct_outputs - activated_output
        # Update the Weights
        adjusted = error * sigmoid_derivative(activated_output)
        weights += np.dot(inputs.T, adjusted)

    def predict(self, X):
        """Return class label after unit step"""
        return None

NameError: name 'self' is not defined

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?